/**
 * Build-time badge inliner (2026-09-06, user-confirmed plan B).
 *
 * Source of truth: `public/assets/gallery/badges/`
 *  - `badge-frame.svg`  the shared stamp frame (two rings), inlined into every
 *                       composed badge so there is exactly ONE place to edit it;
 *  - `<key>.svg`        icon-only artwork (NO baked-in rings), one file per
 *                       badge key used in `content/gallery/items.json`.
 *
 * Each file's ROOT presentation attributes (stroke-width, linecap, linejoin,
 * …) are preserved onto a wrapping <g>, because inlining strips the <svg>
 * root. Everything keeps `stroke="currentColor"` so the composed badge is
 * tinted by CSS (tile accent / hover / dark mode).
 *
 * Output: `components/gallery/badge-art.generated.ts` — committed to the repo;
 * rerun via `npm run badges` (also wired as a `prebuild` hook).
 *
 * The script also cross-checks items.json badge keys and warns about keys
 * without a matching file (those render the placeholder at runtime).
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";

const BADGES_DIR = "public/assets/gallery/badges";
const ITEMS_JSON = "content/gallery/items.json";
const OUT_FILE = "components/gallery/badge-art.generated.ts";
const FRAME_KEY = "badge-frame.svg";

/** Root attributes worth carrying onto the wrapping <g>. */
const KEEP_ATTRS = [
  "fill",
  "stroke",
  "stroke-width",
  "stroke-linecap",
  "stroke-linejoin",
  "stroke-dasharray",
  "opacity",
  "fill-opacity",
  "stroke-opacity",
];

/** Strip prolog/comments and the <svg> root; keep inner markup (ids dropped —
 *  the same frame is inlined into many badges per page, so ids would dupe). */
function innerMarkup(svgText) {
  return svgText
    .replace(/<\?[\s\S]*?\?>/g, "")
    .replace(/<!DOCTYPE[\s\S]*?>/g, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<svg\b[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/\s(id|class)="[^"]*"/g, "")
    .trim();
}

/** Extract whitelisted presentation attributes from an <svg …> root tag. */
function rootAttrs(svgText) {
  const root = svgText.match(/<svg\b([^>]*)>/)?.[1] ?? "";
  const kept = [];
  for (const attr of KEEP_ATTRS) {
    const m = root.match(new RegExp(`\\b${attr}="([^"]*)"`));
    if (m) kept.push(`${attr}="${m[1]}"`);
  }
  return kept.join(" ");
}

/** Wrap inner markup in a <g> carrying the root's presentation attributes. */
function wrapGroup(svgText) {
  const attrs = rootAttrs(svgText);
  const inner = innerMarkup(svgText);
  return attrs ? `<g ${attrs}>${inner}</g>` : `<g>${inner}</g>`;
}

const files = readdirSync(BADGES_DIR).filter((f) => f.endsWith(".svg"));
if (!files.includes(FRAME_KEY)) {
  console.error(`✗ ${FRAME_KEY} not found in ${BADGES_DIR}/ — cannot build badges.`);
  process.exit(1);
}

const frame = wrapGroup(readFileSync(join(BADGES_DIR, FRAME_KEY), "utf8"));
const art = {};
for (const file of files) {
  if (file === FRAME_KEY) continue;
  const key = basename(file, ".svg");
  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(key)) {
    console.warn(`⚠ Skipping "${file}": key must be lowercase kebab-case.`);
    continue;
  }
  art[key] = wrapGroup(readFileSync(join(BADGES_DIR, file), "utf8"));
}

// Cross-check items.json so a stale/misspelled key surfaces at build time.
try {
  const items = JSON.parse(readFileSync(ITEMS_JSON, "utf8"));
  const used = new Set(
    (Array.isArray(items) ? items : []).map((it) => it.badge).filter(Boolean),
  );
  for (const key of used) {
    if (!art[key]) console.warn(`⚠ items.json uses badge "${key}" but ${BADGES_DIR}/${key}.svg is missing — it will render the placeholder.`);
  }
  const unused = Object.keys(art).filter((k) => !used.has(k));
  if (unused.length) {
    console.log(`ℹ ${unused.length} badge file(s) not yet referenced in items.json: ${unused.join(", ")}`);
  }
} catch {
  console.warn(`⚠ Could not read ${ITEMS_JSON} for key cross-check.`);
}

const lines = [
  "/**",
  " * GENERATED by `scripts/build-badges.mjs` — do not edit by hand.",
  " * Sources: public/assets/gallery/badges/*.svg (badge-frame.svg + icons).",
  " * Rerun `npm run badges` after adding or changing badge artwork.",
  " */",
  "",
  "/** Shared stamp frame (two rings) — inlined from badge-frame.svg. */",
  `export const BADGE_FRAME = ${JSON.stringify(frame)};`,
  "",
  "/** Icon-only artwork per badge key, each wrapped with its root attrs. */",
  "export const BADGE_ART: Record<string, string> = {",
  ...Object.entries(art).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  "};",
  "",
];
writeFileSync(OUT_FILE, lines.join("\n"));
console.log(`✓ ${OUT_FILE} written (${Object.keys(art).length} badges + frame).`);
